(()=>{'use strict';
const BK='ratingBackups_v1';
const read=()=>{try{return JSON.parse(localStorage.getItem(BK)||'[]')}catch(e){return[]}};
const data=()=>({version:1,createdAt:new Date().toISOString(),fighters:JSON.parse(JSON.stringify(window.F||[])),ratingDB:localStorage.getItem('ratingDB'),p4p:localStorage.getItem('p4pDB'),champions:localStorage.getItem('manualChampionByWeight'),rankingPositions:localStorage.getItem('manualRankingPositions'),p4pPositions:localStorage.getItem('manualP4PPositions'),news:localStorage.getItem('rankingNews')});
window.createRatingBackup=(label='Перед изменением')=>{const a=read(),d=data();d.label=label;a.unshift(d);localStorage.setItem(BK,JSON.stringify(a.slice(0,30)));return d};
window.restoreRatingBackup=(i)=>{const a=read(),d=a[i];if(!d)return false;if(d.ratingDB!==null)localStorage.setItem('ratingDB',d.ratingDB);if(d.p4p!==null)localStorage.setItem('p4pDB',d.p4p);if(d.champions!==null)localStorage.setItem('manualChampionByWeight',d.champions);if(d.rankingPositions!==null)localStorage.setItem('manualRankingPositions',d.rankingPositions);if(d.p4pPositions!==null)localStorage.setItem('manualP4PPositions',d.p4pPositions);if(d.news!==null)localStorage.setItem('rankingNews',d.news);location.reload();return true};
window.exportRatingBackup=()=>{const b=JSON.stringify(data(),null,2),blob=new Blob([b],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='fighter-ratings-backup-'+new Date().toISOString().replace(/[:.]/g,'-')+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
window.getRatingBackups=()=>read();
window.createRatingBackup('Автоматическая резервная копия');
})();
