(function(){
'use strict';

const num=v=>Number.isFinite(Number(v))?Number(v):0;
const esc2=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const dbSave=()=>{try{localStorage.setItem('ratingDB',JSON.stringify(F));}catch(e){}};
const newsKey='ratingNews';
const getNews=()=>{try{return JSON.parse(localStorage.getItem(newsKey)||'[]')}catch(e){return[]}};
const setNews=a=>localStorage.setItem(newsKey,JSON.stringify(a.slice(0,40)));
function addNews(text){const a=getNews(),day=new Date().toLocaleDateString('ru-RU');if(!a.some(x=>x.text===text&&x.day===day)){a.unshift({text,day,ts:Date.now()});setNews(a)}}
function orderKey(w){return 'ratingOrder_'+w}
function getOrder(w){try{return JSON.parse(localStorage.getItem(orderKey(w))||'[]').map(Number).filter(Boolean)}catch(e){return[]}}
function setOrder(w,ids){localStorage.setItem(orderKey(w),JSON.stringify(ids))}
function applyOrder(arr,w){const ids=getOrder(w);if(!ids.length)return arr;const map=new Map(arr.map(f=>[String(f.id),f])),out=[];ids.forEach(id=>{const f=map.get(String(id));if(f){out.push(f);map.delete(String(id))}});map.forEach(f=>out.push(f));return out}
function rankScore(f){const fights=num(f.wins)+num(f.losses)+num(f.draws),wr=fights?num(f.wins)/fights:0;return num(f.wins)*100+wr*70-num(f.losses)*70+Math.max(0,num(f.streak))*24+(f.champion?20:0)+num(f.activeDefenses)*28+num(f.titleDefenses)*7+num(f.titleWins)*3}
function rankedFixed(w){let a=F.filter(f=>f.weight===w&&!f.champion);a=applyOrder(a,w);if(getOrder(w).length)return a;return a.slice().sort((a,b)=>rankScore(b)-rankScore(a))}
function aggregateP4P(){const map=new Map();F.forEach(f=>{const key=f.name.trim().toLowerCase();if(!map.has(key))map.set(key,{key,name:f.name,country:f.country,wins:0,losses:0,draws:0,streak:0,titleWins:0,titleDefenses:0,activeDefenses:0,championCount:0,weights:[],ids:[]});const x=map.get(key);x.wins+=num(f.wins);x.losses+=num(f.losses);x.draws+=num(f.draws);x.streak=Math.max(x.streak,num(f.streak));x.titleWins+=num(f.titleWins);x.titleDefenses+=num(f.titleDefenses);x.activeDefenses+=num(f.activeDefenses);if(f.champion)x.championCount++;if(!x.weights.includes(f.weight))x.weights.push(f.weight);x.ids.push(f.id)});let a=[...map.values()],ids=getOrder('P4P');if(ids.length){const out=[],used=new Set;ids.forEach(id=>{const x=a.find(v=>v.ids.includes(id));if(x&&!used.has(x.key)){out.push(x);used.add(x.key)}});a.forEach(x=>{if(!used.has(x.key))out.push(x)});return out}return a.sort((a,b)=>(b.championCount-a.championCount)*250+(b.activeDefenses-a.activeDefenses)*40+(b.titleDefenses-a.titleDefenses)*12+(b.streak-a.streak)*22+(b.wins-a.wins)*7-(b.losses-a.losses)*9)}
function profileIdForAgg(x){return x.ids[0]}
function editorCss(){if(document.getElementById('final-editor-css'))return;const s=document.createElement('style');s.id='final-editor-css';s.textContent='.rating-editor{position:relative}.rating-editor-save{position:sticky;bottom:78px;z-index:20;width:100%;margin:10px 0;padding:13px;border:0;border-radius:10px;background:#eee;color:#090a0b;font-weight:900}.rating-editor-row{display:flex;align-items:center;gap:8px;background:#121416;border:1px solid #292c30;border-radius:13px;padding:10px;margin:7px 0;touch-action:none}.rating-editor-row.dragging{opacity:.55}.drag-handle{width:42px;min-width:42px;height:42px;display:flex;align-items:center;justify-content:center;border:1px solid #3a3d41;border-radius:9px;background:#1b1d20;font-size:21px}.editor-rank{width:30px;text-align:center;font-weight:900;font-size:18px}.editor-grow{flex:1;min-width:0}.editor-name{font-weight:900;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.editor-meta{font-size:10px;color:#858a90;margin-top:3px}.editor-champ{width:44px;min-width:44px;height:42px;border:1px solid #3a3d41;border-radius:9px;background:#1b1d20;color:#eee;font-size:18px}@media(max-width:430px){.drag-handle{width:38px;min-width:38px}.editor-rank{width:25px}.rating-editor-row{gap:6px;padding:8px}}';document.head.appendChild(s)}
function editorRow(f,i,isP){const champ=!isP&&!!f.champion,id=isP?String(profileIdForAgg(f)):String(f.id),label=`${f.wins}-${f.losses}-${f.draws} · ${f.activeDefenses} акт. защит`;return `<div class="rating-editor-row" draggable="true" data-id="${esc2(id)}"><div class="editor-rank">${i+1}</div><div class="drag-handle">☰</div><div class="editor-grow"><div class="editor-name">${typeof flag==='function'?flag(f):'🏳️'} ${esc2(f.name)}</div><div class="editor-meta">${label}</div></div>${isP?'':`<button class="editor-champ" onclick="event.stopPropagation();toggleChampion('${esc2(f.id)}')">${champ?'🏆':'○'}</button>`}</div>`}
function makeEditor(isP){editorCss();const source=isP?aggregateP4P():rankedFixed(weight);modalContent.innerHTML=`<div class="rating-editor"><h2>${isP?'Редактирование P4P':'Редактирование рейтинга'}</h2><div class="muted">Тяни бойца за ☰. Чемпионство меняется кнопкой 🏆.</div><div id="rating-editor-list">${source.map((f,i)=>editorRow(f,i,isP)).join('')}</div><button class="rating-editor-save" onclick="saveRankingEditor(${isP})">СОХРАНИТЬ ${isP?'P4P':'РЕЙТИНГ'}</button></div>`;modal.classList.add('show');const list=document.getElementById('rating-editor-list');let drag=null;list.querySelectorAll('.rating-editor-row').forEach(el=>{el.addEventListener('dragstart',()=>{drag=el;el.classList.add('dragging')});el.addEventListener('dragend',()=>{el.classList.remove('dragging');drag=null});el.addEventListener('dragover',e=>{e.preventDefault();if(!drag||drag===el)return;const r=el.getBoundingClientRect();if(e.clientY<r.top+r.height/2)list.insertBefore(drag,el);else list.insertBefore(drag,el.nextSibling)});let sy=0,started=false;el.addEventListener('touchstart',e=>{sy=e.touches[0].clientY;started=true;drag=el},{passive:true});el.addEventListener('touchmove',e=>{if(!started||!drag)return;const t=e.touches[0];if(Math.abs(t.clientY-sy)<8)return;e.preventDefault();const under=document.elementFromPoint(t.clientX,t.clientY)?.closest('.rating-editor-row');if(under&&under!==drag){const r=under.getBoundingClientRect();if(t.clientY<r.top+r.height/2)list.insertBefore(drag,under);else list.insertBefore(drag,under.nextSibling)}},{passive:false});el.addEventListener('touchend',()=>{started=false;drag=null})})}
window.openRankingEditor=()=>makeEditor(false);window.openP4PEditor=()=>makeEditor(true);
window.toggleChampion=function(id){const f=F.find(x=>String(x.id)===String(id));if(!f)return;F.forEach(x=>{if(x.weight===f.weight)x.champion=false});f.champion=true;dbSave()};
window.saveRankingEditor=function(isP){const list=[...document.querySelectorAll('#rating-editor-list .rating-editor-row')];if(isP){const ids=list.map(el=>Number(el.dataset.id)).filter(Boolean),before=aggregateP4P();setOrder('P4P',ids);ids.forEach((id,i)=>{const f=F.find(x=>x.id===id);if(f){const op=before.findIndex(x=>x.ids.includes(id))+1,np=i+1;f.p4pRank=np;if(op&&op!==np){if(np<=5)addNews(`📈 ${f.name} поднялся в TOP-5 P4P — №${np}`);else addNews(`📊 ${f.name}: P4P №${op} → №${np}`)}}});dbSave();closeModal();render();return}const ids=list.map(el=>Number(el.dataset.id)).filter(Boolean),old=rankedFixed(weight),oldPos=new Map(old.map((f,i)=>[String(f.id),i+1]));setOrder(weight,ids);ids.forEach((id,i)=>{const f=F.find(x=>x.id===id);if(!f)return;f.rank=i+1;const op=oldPos.get(String(id)),np=i+1;if(op&&op!==np){if(np===1)addNews(`📈 ${f.name} возглавил рейтинг ${names[weight]}`);else if(np<=5)addNews(`📈 ${f.name} поднялся в TOP-5 ${names[weight]} — №${np}`);else addNews(`📊 ${f.name}: №${op} → №${np} в ${names[weight]}`)}});dbSave();closeModal();render()};
const oldSaveEdit=window.saveEdit;window.saveEdit=function(id){if(typeof oldSaveEdit==='function')oldSaveEdit(id);const f=F.find(x=>String(x.id)===String(id));if(f){f._manualStats=true;dbSave()}};
function migrateStats(){let changed=false;if(!localStorage.getItem('stats_migration_15')){const ps=F.filter(f=>f.name.trim().toLowerCase()==='алекс перейра');const l=ps.find(f=>f.weight==='Light Heavyweight'),m=ps.find(f=>f.weight==='Middleweight');if(l&&m){ps.forEach(f=>f.champion=f===l||f===m);l.activeDefenses=1;m.activeDefenses=1;l.titleDefenses=Math.max(num(l.titleDefenses),1);m.titleDefenses=Math.max(num(m.titleDefenses),1);changed=true}localStorage.setItem('stats_migration_15','1')}const t=F.find(f=>f.name==='Тони Фергюсон');if(t&&!localStorage.getItem('tony_active_fix_15')){t.activeDefenses=0;t.titleDefenses=Math.max(num(t.titleDefenses),3);localStorage.setItem('tony_active_fix_15','1');changed=true}const jan=F.find(f=>f.name==='Пётр Ян');if(jan&&!localStorage.getItem('jan_champ_fix_15')){F.filter(f=>f.weight==='Bantamweight').forEach(f=>f.champion=false);jan.champion=true;jan.titleDefenses=Math.max(num(jan.titleDefenses),1);jan.activeDefenses=Math.max(num(jan.activeDefenses),1);localStorage.setItem('jan_champ_fix_15','1');changed=true}const kai=F.find(f=>f.name==='Кай Аскаура');if(kai&&!localStorage.getItem('kai_champ_fix_15')){F.filter(f=>f.weight==='Flyweight').forEach(f=>f.champion=false);kai.champion=true;localStorage.setItem('kai_champ_fix_15','1');changed=true}if(changed)dbSave()}
migrateStats();
window.home=function(m){const ns=getNews();m.innerHTML=`<div class="card"><div class="hero" style="font-size:25px">НОВОСТИ РЕЙТИНГОВ</div><div class="muted">Последние изменения рейтингов и чемпионств</div></div><div class="list">${ns.map(n=>`<div class="card"><div class="name">${esc2(n.text)}</div><div class="meta">${esc2(n.day)}</div></div>`).join('')||'<div class="card muted">Пока нет новостей рейтингов</div>'}</div>`};
window.rank=function(m){const isP=weight==='P4P';if(isP){const a=aggregateP4P(),top=a.slice(0,15),out=a.slice(15);m.innerHTML=`<div class="card"><div class="muted">P4P</div><div class="hero" style="font-size:25px">P4P</div><div class="muted">Один боец — одна строка. Общий рекорд, чемпионства и защиты из всех весов.</div><button class="primary" style="margin-top:10px" onclick="openP4PEditor()">✎ РЕДАКТИРОВАТЬ P4P</button></div><div class="list">${top.map((f,i)=>p4pDisplay(f,i+1)).join('')}</div>${out.length?`<div class="outside"><div class="outsideTitle">За пределами TOP-15</div><div class="list">${out.map((f,i)=>p4pDisplay(f,i+16)).join('')}</div></div>`:''}`;return}const champ=F.find(f=>f.weight===weight&&f.champion),a=rankedFixed(weight),top=a.slice(0,15),out=a.slice(15);m.innerHTML=`<div class="card"><div class="muted">${names[weight]}</div><div class="hero" style="font-size:25px">Рейтинг</div><div class="muted">Чемпион отдельно · №1 — первый претендент</div><button class="primary" style="margin-top:10px" onclick="openRankingEditor()">✎ РЕДАКТИРОВАТЬ РЕЙТИНГ</button></div>${champ?`<div class="section">🏆 ЧЕМПИОН</div>${normalDisplay(champ,'🏆')}`:''}<div class="section">№1–15 ПРЕТЕНДЕНТЫ</div><div class="list">${top.map((f,i)=>normalDisplay(f,i+1)).join('')}</div>${out.length?`<div class="outside"><div class="outsideTitle">За пределами TOP-15</div><div class="list">${out.map((f,i)=>normalDisplay(f,i+16)).join('')}</div></div>`:''}`};
function normalDisplay(f,pos){return `<div class="row"><div class="rank">${pos}</div><div class="flag">${typeof flag==='function'?flag(f):'🏳️'}</div><div class="grow" onclick="openProfile(${f.id})"><div class="name">${esc2(f.name)} ${f.champion?'🏆':''}</div><div class="meta">${names[f.weight]} · ${f.wins}-${f.losses}-${f.draws} · ${num(f.activeDefenses)} акт. защит</div></div><button class="edit" onclick="editFighter(${f.id})">✎</button></div>`}
function p4pDisplay(f,pos){return `<div class="row"><div class="rank">${pos}</div><div class="flag">${typeof flag==='function'?flag(f):'🏳️'}</div><div class="grow" onclick="openProfile(${profileIdForAgg(f)})"><div class="name">${esc2(f.name)} ${'🏆'.repeat(Math.max(0,f.championCount))}</div><div class="meta">Общий рекорд · ${f.wins}-${f.losses}-${f.draws} · ${f.weights.map(w=>names[w]).join(' / ')}${f.activeDefenses?' · '+f.activeDefenses+' активных защит':''}</div></div></div>`}
editorCss();if(typeof render==='function')render();
})();