(function(){
const num=v=>{const n=Number(v);return Number.isFinite(n)?n:0};
const saveDB=()=>{if(typeof save==='function')save();else localStorage.ratingDB=JSON.stringify(F)};
const close=()=>{if(typeof closeModal==='function')closeModal();else document.getElementById('modal').classList.remove('show')};
const esc=s=>String(s??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));

function normalize(){
 F.forEach(f=>{f.rank=f.rank==null?999:f.rank;f.p4pRank=f.p4pRank==null?999:f.p4pRank;f.p4pManual=!!f.p4pManual;f.rankManual=!!f.rankManual;f.titleDefenses=num(f.titleDefenses);f.activeDefenses=num(f.activeDefenses);f.titleWins=num(f.titleWins);f.streak=num(f.streak)});
 const p=F.filter(f=>f.name.trim().toLowerCase()==='алекс перейра');
 p.forEach(f=>{if(f.weight==='Light Heavyweight'||f.weight==='Middleweight'){f.champion=true;f.activeDefenses=2}});
 F.filter(f=>f.name.trim().toLowerCase()==='тони фергюсон'&&f.champion).forEach(f=>{f.titleDefenses=Math.max(3,num(f.titleDefenses));f.activeDefenses=0});
}
normalize();
const score=f=>num(f.wins)*8-num(f.losses)*12+num(f.streak)*(num(f.streak)>0?18:10)+num(f.titleWins)*18+num(f.titleDefenses)*10+num(f.activeDefenses)*35+(f.champion?70:0);
window.p4p=function(){const map=new Map();F.forEach(f=>{const k=f.name.trim().toLowerCase();if(!map.has(k))map.set(k,{name:f.name,country:f.country,wins:0,losses:0,draws:0,titleWins:0,titleDefenses:0,activeDefenses:0,streak:0,championCount:0,p4pRank:999,manual:false,score:0});const x=map.get(k);x.wins+=num(f.wins);x.losses+=num(f.losses);x.draws+=num(f.draws);x.titleWins+=num(f.titleWins);x.titleDefenses+=num(f.titleDefenses);x.activeDefenses+=num(f.activeDefenses);x.streak=Math.abs(num(f.streak))>Math.abs(x.streak)?num(f.streak):x.streak;x.championCount+=f.champion?1:0;x.score+=score(f);if(f.p4pManual){x.manual=true;x.p4pRank=Math.min(x.p4pRank,num(f.p4pRank)||999)}});return [...map.values()].sort((a,b)=>a.manual&&b.manual?a.p4pRank-b.p4pRank:a.manual!==b.manual?(a.manual?-1:1):b.score-a.score||b.wins-a.losses)};
function dragSetup(id){const list=document.getElementById(id);let dragged=null;if(!list)return;list.querySelectorAll('[draggable=true]').forEach(el=>{el.addEventListener('dragstart',()=>{dragged=el;el.style.opacity='.45'});el.addEventListener('dragend',()=>{dragged=null;el.style.opacity='1';refreshRanks(id)});el.addEventListener('dragover',e=>{e.preventDefault();if(!dragged||dragged===el)return;const r=el.getBoundingClientRect();list.insertBefore(dragged,e.clientY<r.top+r.height/2?el:el.nextSibling);refreshRanks(id)})})}
function refreshRanks(id){document.querySelectorAll('#'+id+' .dragRank').forEach((x,i)=>x.textContent=i+1)}
window.openP4PEditor=function(){const a=p4p();document.getElementById('modalContent').innerHTML=`<h2>✎ Редактор P4P</h2><div class="muted">Перетаскивай бойца за ☰ справа. После этого нажми сохранить.</div><div id="p4pDragList">${a.map((f,i)=>`<div class="card" draggable="true" data-name="${encodeURIComponent(f.name)}" style="display:flex;align-items:center;gap:10px;margin-top:8px;cursor:grab"><div class="rank dragRank">${i+1}</div><div class="grow"><b>${flag({country:f.country})} ${esc(f.name)}</b><div class="muted">${f.wins}-${f.losses}-${f.draws} · ${f.championCount?'🏆'.repeat(Math.min(3,f.championCount)):'без пояса'} · ${f.activeDefenses} активных защит</div></div><div style="font-size:24px;opacity:.65">☰</div></div>`).join('')}</div><div style="position:sticky;bottom:0;background:#111315;padding:10px 0;z-index:2"><button class="primary" onclick="saveP4PEditor()">СОХРАНИТЬ P4P</button></div>`;document.getElementById('modal').classList.add('show');dragSetup('p4pDragList')};
window.saveP4PEditor=function(){document.querySelectorAll('#p4pDragList [data-name]').forEach((el,i)=>{const n=decodeURIComponent(el.dataset.name).trim().toLowerCase();F.filter(f=>f.name.trim().toLowerCase()===n).forEach(f=>{f.p4pRank=i+1;f.p4pManual=true})});saveDB();close();render()};
window.openRankingEditor=function(){if(weight==='P4P')return openP4PEditor();const a=F.filter(f=>f.weight===weight).slice().sort((a,b)=>(num(a.rank)||999)-(num(b.rank)||999)||b.wins-a.wins);document.getElementById('modalContent').innerHTML=`<h2>✎ ${names[weight]} — рейтинг</h2><div class="muted">Перетаскивай бойца за ☰ справа. Чемпионство меняется в профиле. После перестановки нажми сохранить.</div><div id="rankDragList">${a.map((f,i)=>`<div class="card" draggable="true" data-id="${f.id}" style="display:flex;align-items:center;gap:10px;margin-top:8px;cursor:grab"><div class="rank dragRank">${i+1}</div><div class="grow"><b>${flag(f)} ${esc(f.name)}</b><div class="muted">${f.wins}-${f.losses}-${f.draws} · ${f.champion?'🏆 Чемпион':''}</div></div><div style="font-size:24px;opacity:.65">☰</div></div>`).join('')}</div><div style="position:sticky;bottom:0;background:#111315;padding:10px 0;z-index:2"><button class="primary" onclick="saveRankingEditor()">СОХРАНИТЬ РЕЙТИНГ</button></div>`;document.getElementById('modal').classList.add('show');dragSetup('rankDragList')};
window.saveRankingEditor=function(){if(weight==='P4P')return saveP4PEditor();document.querySelectorAll('#rankDragList [data-id]').forEach((el,i)=>{const f=F.find(x=>String(x.id)===el.dataset.id);if(f){f.rank=i+1;f.rankManual=true}});saveDB();close();render()};
window.editFighter=function(id){const f=F.find(x=>x.id===id);if(!f)return;document.getElementById('modalContent').innerHTML=`<h2>✎ ${flag(f)} ${esc(f.name)}</h2><label>Вес</label><select id="ef_weight">${W.filter(x=>x!=='P4P').map(w=>`<option value="${w}" ${f.weight===w?'selected':''}>${names[w]}</option>`).join('')}</select><label>Победы</label><input id="ef_w" type="number" min="0" value="${num(f.wins)}"><label>Поражения</label><input id="ef_l" type="number" min="0" value="${num(f.losses)}"><label>Ничьи</label><input id="ef_d" type="number" min="0" value="${num(f.draws)}"><label>Серия</label><input id="ef_s" type="number" value="${num(f.streak)}"><label>Общие защиты</label><input id="ef_td" type="number" min="0" value="${num(f.titleDefenses)}"><label>Активные защиты</label><input id="ef_ad" type="number" min="0" value="${num(f.activeDefenses)}"><label>Завоеваний пояса</label><input id="ef_tw" type="number" min="0" value="${num(f.titleWins)}"><label>Позиция в весе</label><input id="ef_rank" type="number" min="1" value="${num(f.rank)||999}"><label>P4P позиция</label><input id="ef_p4p" type="number" min="1" value="${num(f.p4pRank)||999}"><label><input id="ef_champ" type="checkbox" ${f.champion?'checked':''}> Чемпион</label><div style="position:sticky;bottom:0;background:#111315;padding:10px 0"><button class="primary" onclick="saveFighterEdit(${id})">СОХРАНИТЬ БОЙЦА</button></div>`;document.getElementById('modal').classList.add('show')};
window.saveFighterEdit=function(id){const f=F.find(x=>x.id===id);if(!f)return;f.weight=document.getElementById('ef_weight').value;f.wins=Math.max(0,num(document.getElementById('ef_w').value));f.losses=Math.max(0,num(document.getElementById('ef_l').value));f.draws=Math.max(0,num(document.getElementById('ef_d').value));f.streak=num(document.getElementById('ef_s').value);f.titleDefenses=Math.max(0,num(document.getElementById('ef_td').value));f.activeDefenses=Math.max(0,num(document.getElementById('ef_ad').value));f.titleWins=Math.max(0,num(document.getElementById('ef_tw').value));f.rank=Math.max(1,num(document.getElementById('ef_rank').value)||999);f.p4pRank=Math.max(1,num(document.getElementById('ef_p4p').value)||999);f.p4pManual=true;f.champion=document.getElementById('ef_champ').checked;saveDB();close();render()};
const oldRank=window.rank;window.rank=function(m){oldRank(m);m.querySelectorAll('.primary').forEach(b=>{if((b.textContent||'').includes('РЕДАКТИРОВАТЬ РЕЙТИНГ')||(b.textContent||'').includes('РЕДАКТИРОВАТЬ P4P'))b.remove()});const card=m.querySelector('.card');if(card){const b=document.createElement('button');b.className='primary';b.style.marginTop='10px';b.textContent=weight==='P4P'?'✎ РЕДАКТИРОВАТЬ P4P':'✎ РЕДАКТИРОВАТЬ РЕЙТИНГ';b.onclick=openRankingEditor;card.appendChild(b)}};
window.addFight=function(){const select=document.getElementById('bf')||document.getElementById('f'),resultEl=document.getElementById('br')||document.getElementById('r');if(!select||!resultEl)return;const f=F.find(x=>x.id==select.value);if(!f)return;const raw=resultEl.value;const result=(raw==='W'||raw==='1'||raw==='WIN')?'WIN':(raw==='L'||raw==='0'||raw==='LOSS'?'LOSS':'DRAW');const wasChamp=!!f.champion;f.history=f.history||[];if(result==='WIN'){f.wins=num(f.wins)+1;f.streak=f.streak>0?f.streak+1:1;if(wasChamp){f.titleDefenses=num(f.titleDefenses)+1;f.activeDefenses=num(f.activeDefenses)+1}}else if(result==='LOSS'){f.losses=num(f.losses)+1;f.streak=f.streak<0?f.streak-1:-1;f.history.unshift({result:'LOSS',method:document.getElementById('bm')?.value||'',round:document.getElementById('bround')?.value||'',date:new Date().toLocaleDateString('ru-RU')});if(wasChamp){f.champion=false;f.activeDefenses=0;const c=F.filter(x=>x.weight===f.weight&&!x.champion&&num(x.streak)>=2).sort((a,b)=>(num(a.rank)||999)-(num(b.rank)||999)||num(b.streak)-num(a.streak))[0];if(c){c.champion=true;c.activeDefenses=0}}saveDB();weight=f.weight;page='rank';render();return}else{f.draws=num(f.draws)+1;f.streak=0}f.history.unshift({result,method:document.getElementById('bm')?.value||'',round:document.getElementById('bround')?.value||'',date:new Date().toLocaleDateString('ru-RU')});saveDB();weight=f.weight;page='rank';render()};
saveDB();if(typeof render==='function')render();
})();