(function(){'use strict';
const n=v=>Number.isFinite(Number(v))?Number(v):0;
const esc=s=>String(s??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
function q(f){const t=n(f.wins)+n(f.losses)+n(f.draws),wr=t?n(f.wins)/t:0;return n(f.wins)*100+wr*70-n(f.losses)*65+Math.max(0,n(f.streak))*18+(f.champion?25:0)+n(f.activeDefenses)*18+n(f.titleDefenses)*5+n(f.titleWins)*3;}
function ordered(w){return F.filter(f=>f.weight===w&&!f.champion).slice().sort((a,b)=>{const ar=n(a.rank),br=n(b.rank),am=ar>0&&ar<99,bm=br>0&&br<99;if(am&&bm){const diff=q(b)-q(a);if(Math.abs(diff)>180)return diff;return ar-br}if(am&&!bm)return ar<=15?-1:q(b)-q(a);if(!am&&bm)return br<=15?1:q(b)-q(a);return q(b)-q(a)});}
function aggP4P(){const m=new Map();F.forEach(f=>{const k=f.name.trim().toLowerCase();if(!m.has(k))m.set(k,{name:f.name,country:f.country,weight:f.weight,wins:0,losses:0,draws:0,streak:0,titleWins:0,titleDefenses:0,activeDefenses:0,championCount:0,weights:[],p4pRank:999});const x=m.get(k);x.wins+=n(f.wins);x.losses+=n(f.losses);x.draws+=n(f.draws);x.titleWins+=n(f.titleWins);x.titleDefenses+=n(f.titleDefenses);x.activeDefenses+=n(f.activeDefenses);x.streak=Math.max(x.streak,n(f.streak));if(f.champion)x.championCount++;if(!x.weights.includes(f.weight))x.weights.push(f.weight);if(n(f.p4pRank)>0)x.p4pRank=Math.min(x.p4pRank,n(f.p4pRank));});return [...m.values()].sort((a,b)=>{const am=a.p4pRank<999,bm=b.p4pRank<999;if(am&&bm)return a.p4pRank-b.p4pRank;if(am&&!bm)return -1;if(!am&&bm)return 1;return (b.championCount-a.championCount)*250+(b.activeDefenses-a.activeDefenses)*35+(b.titleDefenses-a.titleDefenses)*12+(b.streak-a.streak)*20+(b.wins-a.wins)*6-(b.losses-a.losses)*8;});}
function frow(f,pos,isP){const ch=isP?n(f.championCount)>0:!!f.champion;const id=isP?'':String(f.id);return `<div class="row"><div class="rank">${pos}</div><div class="flag">${typeof flag==='function'?flag(f):'🏳️'}</div><div class="grow" onclick="openProfile(${id||JSON.stringify((F.find(x=>x.name===f.name)||{}).id)})"><div class="name">${esc(f.name)} ${ch?'🏆'.repeat(Math.max(1,isP?n(f.championCount):1)):''}</div><div class="meta">${isP?'Общий рекорд':names[f.weight]} · ${f.wins}-${f.losses}-${f.draws}${isP&&f.weights.length?' · '+f.weights.map(w=>names[w]).join(' / '):''}${isP&&f.activeDefenses?' · '+f.activeDefenses+' активных защит':''}</div></div></div>`;}
window.rank=function(m){
 const isP=weight==='P4P';
 if(isP){const a=aggP4P(),top=a.slice(0,15),out=a.slice(15);m.innerHTML=`<div class="card"><div class="muted">RANKING</div><div class="hero" style="font-size:25px">P4P</div><div class="muted">Один боец — одна строка. Рекорд, чемпионства и защиты объединены.</div><button class="primary" style="margin-top:10px" onclick="openP4PEditor()">✎ РЕДАКТИРОВАТЬ P4P</button></div><div class="list">${top.map((f,i)=>frow(f,i+1,true)).join('')}</div>${out.length?`<div class="outside"><div class="outsideTitle">За пределами TOP-15</div><div class="list">${out.map((f,i)=>frow(f,i+16,true)).join('')}</div></div>`:''}`;return;}
 const champ=F.find(f=>f.weight===weight&&f.champion),a=ordered(weight),top=a.slice(0,15),out=a.slice(15);m.innerHTML=`<div class="card"><div class="muted">${names[weight]}</div><div class="hero" style="font-size:25px">Рейтинг</div><div class="muted">Чемпион отдельно · №1 — первый претендент</div><button class="primary" style="margin-top:10px" onclick="openRankingEditor()">✎ РЕДАКТИРОВАТЬ РЕЙТИНГ</button></div>${champ?`<div class="section">🏆 ЧЕМПИОН</div>${frow(champ,'🏆',false)}`:''}<div class="section">№1–15 ПРЕТЕНДЕНТЫ</div><div class="list">${top.map((f,i)=>frow(f,i+1,false)).join('')}</div>${out.length?`<div class="outside"><div class="outsideTitle">За пределами TOP-15</div><div class="list">${out.map((f,i)=>frow(f,i+16,false)).join('')}</div></div>`:''}`;
};
})();