(()=>{'use strict';
const POS='manualP4PPositions_v2',BACK='ratingBackups_v1';
const read=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch(e){return d}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const saveDB=()=>localStorage.setItem('ratingDB',JSON.stringify(F));
const backup=label=>{const a=read(BACK,[]);a.unshift({label,createdAt:new Date().toISOString(),ratingDB:localStorage.getItem('ratingDB'),p4p:localStorage.getItem('p4pDB'),champions:localStorage.getItem('manualChampionByWeight'),p4pPositions:localStorage.getItem(POS),news:localStorage.getItem('rankingNews')});write(BACK,a.slice(0,50))};
const key=f=>f.name;
function aggregateP4P(){const m=new Map();F.forEach(f=>{let x=m.get(key(f));if(!x){x={name:f.name,country:f.country,ids:[],wins:0,losses:0,draws:0,activeDefenses:0,titleDefenses:0,titles:0,streak:0,champions:[]};m.set(key(f),x)}x.ids.push(f.id);x.wins+=+f.wins||0;x.losses+=+f.losses||0;x.draws+=+f.draws||0;x.activeDefenses+=+f.activeDefenses||0;x.titleDefenses+=+f.titleDefenses||0;x.titles+=(f.champion?1:0);if((f.streak||0)>x.streak)x.streak=f.streak;if(f.champion)x.champions.push(f.weight)});return [...m.values()]}
function p4pList(){const a=aggregateP4P(),pos=read(POS,{});a.sort((x,y)=>{const px=pos[x.name]??999,py=pos[y.name]??999;return px-py||y.titles-x.titles||y.activeDefenses-x.activeDefenses||(y.wins-y.losses)-(x.wins-x.losses)||y.streak-x.streak});a.forEach((x,i)=>x.rank=pos[x.name]??i+1);return a}
let editMode=false;
const esc=s=>String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/\"/g,'&quot;');
function p4pRow(x,i){return `<div class="row master-p4p-row" data-name="${esc(x.name)}"><div class="rank">${i}</div><div class="flag">${FLAGS[x.country]||'🏳️'}</div><div class="grow"><div class="name">${esc(x.name)} ${x.titles?('🏆'.repeat(Math.min(2,x.titles))):''}</div><div class="meta">P4P · ${x.wins}-${x.losses}-${x.draws} · серия +${Math.max(0,x.streak)} · ${x.activeDefenses} активных защит</div></div>${editMode?`<div class="drag-handle" draggable="true" data-name="${esc(x.name)}">☰</div>`:''}<button class="edit" onclick="event.stopPropagation();masterOpenByName('${esc(x.name)}')">✎</button></div>`}
function masterOpenByName(name){const f=F.find(x=>x.name===name);if(f&&typeof openProfile==='function')openProfile(f.id)}
window.masterOpenByName=masterOpenByName;
function p4pMasterRank(m){if(weight==='P4P'){const a=p4pList();m.innerHTML=`<div class="card"><div class="muted">RANKING</div><div class="hero" style="font-size:25px">P4P</div><div class="muted">Единый рейтинг. Позиции сохраняются отдельно.</div><button class="primary master-edit-btn" style="margin-top:10px" onclick="masterToggleEdit()">${editMode?'ГОТОВО':'✎ РЕДАКТИРОВАТЬ P4P'}</button></div><div class="list master-drag-list">${a.slice(0,15).map((x,i)=>p4pRow(x,i+1)).join('')}</div><div class="outside"><div class="outsideTitle">За пределами TOP-15</div><div class="list">${a.slice(15).map((x,i)=>p4pRow(x,i+16)).join('')}</div></div>${editMode?'<button class="primary master-save master-save-fixed" onclick="masterSaveP4P()">СОХРАНИТЬ P4P</button>':''}`;if(editMode)bindDrag();return true}}
function weightList(){return F.filter(f=>f.weight===weight).slice().sort((a,b)=>(a.rank||99)-(b.rank||99));}
function weightRow(f,i){return `<div class="row master-weight-row" data-id="${f.id}"><div class="rank">${i}</div><div class="flag">${flag(f)}</div><div class="grow" onclick="openProfile(${f.id})"><div class="name">${f.name} ${f.champion?'🏆':''}</div><div class="meta">${names[f.weight]} · ${f.wins}-${f.losses}-${f.draws} · серия ${f.streak>0?'+'+f.streak:f.streak}</div></div>${editMode?`<div class="drag-handle" draggable="true" data-id="${f.id}">☰</div>`:''}<button class="edit" onclick="editFighter(${f.id})">✎</button></div>`}
function masterWeight(m){const a=weightList();m.innerHTML=`<div class="card"><div class="muted">RANKING</div><div class="hero" style="font-size:25px">${names[weight]}</div><button class="primary master-edit-btn" style="margin-top:10px" onclick="masterToggleEdit()">${editMode?'ГОТОВО':'✎ РЕДАКТИРОВАТЬ РЕЙТИНГ'}</button></div><div class="list master-drag-list">${a.slice(0,15).map((f,i)=>weightRow(f,i+1)).join('')}</div><div class="outside"><div class="outsideTitle">За пределами TOP-15</div><div class="list">${a.slice(15).map((f,i)=>weightRow(f,i+16)).join('')}</div></div>${editMode?'<button class="primary master-save master-save-fixed" onclick="masterSaveWeight()">СОХРАНИТЬ РЕЙТИНГ</button>':''}`;if(editMode)bindDrag();return true}
function bindDrag(){document.querySelectorAll('.drag-handle').forEach(h=>{h.addEventListener('dragstart',e=>e.dataTransfer.setData('text/plain',h.dataset.id||h.dataset.name));h.addEventListener('dragend',()=>document.body.classList.remove('dragging'))});document.querySelectorAll('.master-drag-list .row').forEach(r=>{r.addEventListener('dragover',e=>e.preventDefault());r.addEventListener('drop',e=>{e.preventDefault();const id=e.dataTransfer.getData('text/plain');const rows=[...document.querySelectorAll('.master-drag-list .row')];const from=rows.findIndex(x=>(x.dataset.id||x.dataset.name)===id),to=rows.indexOf(r);if(from<0||to<0||from===to)return;const order=rows.map(x=>x.dataset.id||x.dataset.name);order.splice(to,0,order.splice(from,1)[0]);if(weight==='P4P'){const p=read(POS,{});order.forEach((n,i)=>p[n]=i+1);write(POS,p)}else{order.forEach((n,i)=>{const f=F.find(x=>String(x.id)===String(n));if(f)f.rank=i+1});saveDB()}render()})})}
window.masterToggleEdit=()=>{editMode=!editMode;render()};
window.masterSaveP4P=()=>{backup('Перед сохранением P4P');const p=read(POS,{});document.querySelectorAll('.master-p4p-row').forEach((r,i)=>p[r.dataset.name]=i+1);write(POS,p);editMode=false;render()};
window.masterSaveWeight=()=>{backup('Перед сохранением рейтинга');document.querySelectorAll('.master-weight-row').forEach((r,i)=>{const f=F.find(x=>String(x.id)===String(r.dataset.id));if(f)f.rank=i+1});saveDB();editMode=false;render()};
const oldRender=window.render;window.render=function(){const m=document.getElementById('main');if(page==='rank'){if(weight==='P4P')p4pMasterRank(m);else masterWeight(m);document.getElementById('weights').innerHTML=W.map(x=>`<button class="${weight===x?'on':''}" onclick="weight='${x}';page='rank';editMode=false;render()">${x==='P4P'?x:names[x]}</button>`).join('');return}return oldRender.apply(this,arguments)};
const oldSaveEdit=window.saveEdit;window.saveEdit=function(id){backup('Перед редактированием бойца');oldSaveEdit.apply(this,arguments);saveDB()};
if(!localStorage.getItem('integrity_v18')){const p=F.filter(f=>f.name==='Алекс Перейра');if(p.length&&p.reduce((s,f)=>s+f.wins,0)===9){const target=p.find(f=>f.weight==='Light Heavyweight');if(target)target.wins=7}localStorage.setItem('integrity_v18','1');saveDB()}
/* v20: load the stable layer with a cache-busting URL. */
const stable=document.createElement('script');stable.src='stabilizer_v19.js?v=20';document.body.appendChild(stable);
})();