(()=>{'use strict';
/* v23: separate HOME news from rankings + hide active defenses for non-champions. */
const KEY='ratingDB',NEWS='rankingNews_v3';
const read=(k,d)=>{try{const v=localStorage.getItem(k);return v===null?d:JSON.parse(v)}catch(e){return d}};
const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
function addStyles(){if(document.getElementById('v23styles'))return;const s=document.createElement('style');s.id='v23styles';s.textContent=`.v23-news-head{display:flex;align-items:center;gap:10px;font-size:25px;font-weight:900;margin:4px 0}.v23-news-card{background:#121416;border:1px solid #292c30;border-radius:14px;padding:14px;margin:8px 0}.v23-news-date{font-size:10px;color:#777;margin-bottom:6px}.v23-news-item{font-size:14px;font-weight:800;line-height:1.35}.v23-news-up{font-size:22px}.v23-news-empty{color:#858a90;font-size:13px;padding:10px 0}.v23-news-sub{font-size:11px;color:#858a90;margin:4px 0 14px}`;document.head.appendChild(s)}
function hideNonChampionDefense(){const F=Array.isArray(window.F)?window.F:read(KEY,[]);document.querySelectorAll('.v21-weight').forEach(row=>{const f=F.find(x=>String(x.id)===String(row.dataset.id));if(!f||f.champion)return;const meta=row.querySelector('.meta');if(!meta)return;meta.textContent=meta.textContent.replace(/\s*·\s*\d+\s+акт\.\s+защит/g,'').replace(/\s*·\s*\d+\s+защит(?=\s*$)/g,'')})}
function renderNewsHome(m){const news=read(NEWS,[]);m.innerHTML=`<div class="card"><div class="muted">PERSONAL DATABASE</div><div class="hero">${(Array.isArray(window.F)?window.F:read(KEY,[])).length}</div><div class="muted">бойцов в базе</div></div><div class="v23-news-head">📰 НОВОСТИ</div><div class="v23-news-sub">Изменения чемпионств и рейтингов</div>${news.length?news.slice(0,30).map(x=>{const parts=String(x).split(' — ');return `<div class="v23-news-card"><div class="v23-news-date">${esc(parts[0]||'')}</div><div class="v23-news-item"><span class="v23-news-up">${/опустился|пораж/i.test(x)?'↘️':'↗️'}</span> ${esc(parts.slice(1).join(' — ')||x)}</div></div>`}).join(''):'<div class="v23-news-empty">Пока нет изменений рейтингов.</div>'}`}
function install(){addStyles();const old=window.render;if(typeof old!=='function')return;window.render=function(){const result=old.apply(this,arguments);try{if(window.page==='home'){const m=document.getElementById('main');if(m)renderNewsHome(m)}else if(window.page==='rank'&&window.weight!=='P4P'){hideNonChampionDefense()}}catch(e){console.error('v23 patch',e)}return result};if(window.page==='home'){setTimeout(()=>{const m=document.getElementById('main');if(m)renderNewsHome(m)},0)}}
install();
})();
