(function(){
const extra=[
['Томас Алмейда','Bantamweight','BR'],['Рафаэл Ассунсао','Bantamweight','BR'],['Ренан Барао','Bantamweight','BR'],['Алекс Касерес','Featherweight','US'],['Джонатан Мартинес','Bantamweight','US'],['Марлон Вера','Bantamweight','EC'],['Педро Муньос','Bantamweight','BR'],['Кайлер Филлипс','Bantamweight','US'],['Рики Саймон','Bantamweight','US'],['Джимми Ривера','Bantamweight','US'],['Фрэнки Эдгар','Bantamweight','US'],['Дейвисон Фигейредо','Bantamweight','BR'],['Сонг Ядонг','Bantamweight','CN'],['Марио Баутиста','Bantamweight','US'],['Пейтон Тэлботт','Bantamweight','US'],['Айманн Захаби','Bantamweight','CA'],['Генри Сехудо','Bantamweight','US'],
['Йаир Родригес','Featherweight','MX'],['Альджамейн Стерлинг','Featherweight','US'],['Диего Лопес','Featherweight','BR'],['Юссеф Залал','Featherweight','MA'],['Дэвид Онама','Featherweight','UG'],['Мелкизаэль Коста','Featherweight','BR'],['Аарон Пико','Featherweight','US'],['Натаниль Вуд','Featherweight','GB'],['Пэт Сабатини','Featherweight','US'],['Морган Шарьер','Featherweight','FR'],['Андре Фили','Featherweight','US'],['Кэлвин Каттар','Featherweight','US'],['Брайс Митчелл','Featherweight','US'],['Чарльз Джордейн','Featherweight','CA'],['Дэн Иге','Featherweight','US'],['Куб Свонсон','Featherweight','US'],['Содик Юсуфф','Featherweight','NG'],['Джереми Стивенс','Featherweight','US'],['Ду Хо Чой','Featherweight','KR'],
['Ренато Мойкано','Lightweight','BR'],['Грант Доусон','Lightweight','US'],['Игнасио Бахамондес','Lightweight','CL'],['Крис Дункан','Lightweight','GB'],['Куиллан Салкильд','Lightweight','AU'],['Фарес Зиам','Lightweight','FR'],['Лудовит Кляйн','Lightweight','SK'],['Джаред Гордон','Lightweight','US'],['Драккар Клозе','Lightweight','US'],['Терренс Маккинни','Lightweight','US'],['Мэтт Фревола','Lightweight','US'],['Дэниэл Зеллхубер','Lightweight','MX'],['Джалин Тёрнер','Lightweight','US'],['Мануэль Торрес','Lightweight','MX'],['Чейз Хупер','Lightweight','US'],['Александр Эрнандес','Lightweight','US'],['Дрю Добер','Lightweight','US'],['Пол Фелдер','Lightweight','US'],['Майкл Чьеза','Welterweight','US'],['Эдди Альварес','Lightweight','US'],['Энтони Петтис','Lightweight','US'],['Клей Гвида','Lightweight','US'],['Джим Миллер','Lightweight','US'],['Кевин Ли','Welterweight','US'],
['Гилберт Бёрнс','Welterweight','BR'],['Колби Ковингтон','Welterweight','US'],['Иэн Мачадо Гарри','Welterweight','IE'],['Геофф Нил','Welterweight','US'],['Висенте Луке','Welterweight','BR'],['Стивен Томпсон','Welterweight','US'],['Брайан Баттл','Welterweight','US'],['Рэнди Браун','Welterweight','US'],['Демьян Майя','Welterweight','BR'],['Нил Мэгни','Welterweight','US'],['Джонни Хендрикс','Welterweight','US'],['Карлос Кондит','Welterweight','US'],['Робби Лоулер','Welterweight','US'],['Джордж Сент-Пьер','Welterweight','CA'],['Ник Диас','Welterweight','US'],['Нейт Диас','Welterweight','US'],['Хорхе Масвидаль','Welterweight','US'],['Тайрон Вудли','Welterweight','US'],['Кевин Холланд','Welterweight','US'],['Шавкат Рахмонов','Welterweight','KZ'],['Габриэль Бонфим','Welterweight','BR'],['Миктибек Оролбай','Welterweight','KG'],['Джоэл Альварес','Welterweight','ES'],['Ярослав Амосов','Welterweight','UA'],['Николас Далби','Welterweight','DK'],['Сэм Паттерсон','Welterweight','GB'],
['Хамзат Чимаев','Middleweight','AE'],['Джаред Каннонье','Middleweight','US'],['Марвин Веттори','Middleweight','IT'],['Джек Херманссон','Middleweight','SE'],['Брендан Аллен','Middleweight','US'],['Роман Долидзе','Middleweight','GE'],['Кайо Борральо','Middleweight','BR'],['Крис Кёртис','Middleweight','US'],['Эдмен Шахбазян','Middleweight','US'],['Люк Рокхолд','Middleweight','US'],['Ник Диас','Middleweight','US'],['Дэн Хендерсон','Middleweight','US'],['Андерсон Силва','Middleweight','BR'],['Вандерлей Силва','Middleweight','BR'],['Майкл Биспинг','Middleweight','GB'],['Витор Белфорт','Middleweight','BR'],['Лиото Мачида','Middleweight','BR'],['Крис Вайдман','Middleweight','US'],['Роберт Уиттакер','Middleweight','AU'],['Нассурдин Имавов','Middleweight','FR'],['Дрикус Дю Плесси','Middleweight','ZA'],['Грегори Родригес','Middleweight','BR'],['Икрам Алискеров','Middleweight','RU'],['Кристиан Лерой Дункан','Middleweight','GB'],['Абус Магомедов','Middleweight','DE'],['Брунно Феррейра','Middleweight','BR'],['Нурсултон Рузибоев','Middleweight','UZ'],
['Джамахал Хилл','Light Heavyweight','US'],['Жири Прохазка','Light Heavyweight','CZ'],['Александар Ракич','Light Heavyweight','AT'],['Никита Крылов','Light Heavyweight','RU'],['Энтони Смит','Light Heavyweight','US'],['Джонни Уокер','Light Heavyweight','BR'],['Халил Раунтри','Light Heavyweight','US'],['Витор Петрино','Light Heavyweight','BR'],['Богдан Гуськов','Light Heavyweight','UZ'],['Дастин Джакоби','Light Heavyweight','US'],['Чак Лидделл','Light Heavyweight','US'],['Тито Ортис','Light Heavyweight','US'],['Рашад Эванс','Light Heavyweight','US'],['Даниэль Кормье','Light Heavyweight','US'],['Куинтон Джексон','Light Heavyweight','US'],['Андерсон Силва','Light Heavyweight','BR'],['Александр Густафссон','Light Heavyweight','SE'],['Форрест Гриффин','Light Heavyweight','US'],['Энтони Джонсон','Light Heavyweight','US'],['Илир Латифи','Light Heavyweight','SE'],['Гловер Тейшейра','Light Heavyweight','BR'],['Овинс Сент-Прю','Light Heavyweight','US'],['Гокхан Саки','Light Heavyweight','TR'],['Занг Минъян','Light Heavyweight','CN'],['Модестас Букаускас','Light Heavyweight','LT'],['Ион Куцелаба','Light Heavyweight','MD'],['Оумар Си','Light Heavyweight','FR'],['Навахо Стирлинг','Light Heavyweight','NZ'],['Иво Бараньевский','Light Heavyweight','PL'],
['Стипе Миочич','Heavyweight','US'],['Деррик Льюис','Heavyweight','US'],['Александр Волков','Heavyweight','RU'],['Жаилтон Алмейда','Heavyweight','BR'],['Тай Туиваса','Heavyweight','AU'],['Марчин Тыбура','Heavyweight','PL'],['Сергей Павлович','Heavyweight','RU'],['Сергей Спивак','Heavyweight','MD'],['Вальдо Кортес-Акоста','Heavyweight','DO'],['Шамиль Газиев','Heavyweight','BH'],['Джош Хоккит','Heavyweight','US'],['Валтер Уокер','Heavyweight','BR'],['Ризван Куниев','Heavyweight','RU'],['Анте Делия','Heavyweight','HR'],['Талиссон Тейшейра','Heavyweight','BR'],['Мик Паркин','Heavyweight','GB'],['Брэндо Перичич','HR','HR'],['Кеннеди Нзечукву','Heavyweight','NG'],['Райан Спэнн','Heavyweight','US'],['Алистар Оверим','Heavyweight','NL'],['Джуниор дос Сантос','Heavyweight','BR'],['Марк Керр','Heavyweight','US'],['Уолт Харрис','Heavyweight','US'],['Дон Фрай','Heavyweight','US'],['Алексей Олейник','Heavyweight','RU'],['Александр Романов','Heavyweight','MD'],['Стефан Струве','Heavyweight','NL'],['Кимбо Слайс','Heavyweight','BS'],['Дэн Северн','Heavyweight','US'],['Бас Руттен','Heavyweight','NL'],['Жаирзиньо Розенстрайк','Heavyweight','SR'],['Каин Веласкес','Heavyweight','US'],['Марк Коулман','Heavyweight','US'],['Рэнди Кутюр','Heavyweight','US'],['Кен Шамрок','US','US'],['Танк Эбботт','Heavyweight','US']
];
const codes={EC:'🇪🇨',CN:'🇨🇳',UG:'🇺🇬',MA:'🇲🇦',CL:'🇨🇱',SK:'🇸🇰',IT:'🇮🇹',SE:'🇸🇪',CZ:'🇨🇿',AT:'🇦🇹',MD:'🇲🇩',TR:'🇹🇷',LT:'🇱🇹',BH:'🇧🇭',DO:'🇩🇴',HR:'🇭🇷',UA:'🇺🇦',KG:'🇰🇬',UZ:'🇺🇿',BS:'🇧🇸',SR:'🇸🇷'};
Object.assign(FLAGS,codes);
extra.forEach(x=>{const name=x[0],w=x[1];if(!W.includes(w))return;if(!F.some(f=>f.name===name&&f.weight===w)){F.push({id:Date.now()+Math.random(),name:name,weight:w,country:x[2],wins:0,losses:0,draws:0,rank:99,champion:false,titleWins:0,titleDefenses:0,activeDefenses:0,streak:0,history:[],ufc6:true});}});
save();render();
})();