(()=>{'use strict';
/* STABLE UI LAYER v19
   This file is intentionally the LAST script in index.html.
   It prevents the older UI override files from changing the initial screen or P4P view.
   It NEVER changes W/L/D, history, defenses or championships automatically.
*/
const NEWS_KEY='fighterRatingsNewsV1';
const P4P_POS_KEY='manualP4PPositions_v2';
const readJSON=(k,d)=>{try{const v=JSON.parse(localStorage.getItem(k));return v??d}catch{return d}};
const writeJSON=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const n=v=>Number.isFinite(Number(v))?Number(v):0;
const backupStable=label=>{try{const a=readJSON('ratingBackups_v1',[]);a.unshift({label,createdAt:new Date().toISOString(),ratingDB:localStorage.getItem('ratingDB'),p4pPositions:localStorage.getItem(P4P_POS_KEY),news:localStorage.getItem(NEWS_KEY)});writeJSON('ratingBackups_v1',a.slice(0,50))}catch{}};
const aggregate=()=>{const m=new Map();(window.F||[]).forEach(f=>{let x=m.get(f.name);if(!x){x={name:f.name,country:f.country,ids:[],wins:0,losses:0,draws:0,activeDefenses:0,titleDefenses:0,titles:0,streak:0};m.set(f.name,x)}x.ids.push(f.id);x.wins+=n(f.wins);x.losses+=n(f.losses);x.draws+=n(f.draws);x.activeDefenses+=n(f.activeDefenses);x.titleDefenses+=n(f.titleDefenses);x.titles+=f.champion?1:0;x.streak=Math.max(x.streak,n(f.streak))});return [...m.values()]};
const getP4P=()=>{const pos=readJSON(P4P_POS_KEY,{}),a=aggregate();a.sort((x,y)=>{const px=pos[x.name]??999,py=pos[y.name]??999;if(px!==py)return px-py;return (y.titles-x.titles)||(y.activeDefenses-x.activeDefenses)||((y.wins-y.losses)-(x.wins-x.losses))||(y.streak-x.streak)||x.name.localeCompare(y.name,'ru')});return a};
const ensureP4PPositions=()=>{let pos=readJSON(P4P_POS_KEY,null);if(!pos||typeof pos!=='object'||Array.isArray(pos)){pos={};aggregate().forEach((x,i)=>pos[x.name]=i+1);writeJSON(P4P_POS_KEY,pos);return}let max=Object.values(pos).reduce((m,v)=>Math.max(m,n(v)),0);aggregate().forEach(x=>{if(pos[x.name]==null){pos[x.name]=++max}});writeJSON(P4P_POS_KEY,pos)};
const news=()=>{const a=readJSON(NEWS_KEY,[]);if(!a.length)return '<div class="card"><div class="hero" style="font-size:25px">НОВОСТИ РЕЙТИНГОВ</div><div class="muted">Пока изменений рейтингов нет.</div></div>';return `<div class="card"><div class="muted">РЕЙТИНГИ</div><div class="hero" style="font-size:25px">НОВОСТИ РЕЙТИНГОВ</div><div class="muted">Последние изменения рейтингов и чемпионств</div></div><div class="list">${a.slice(0,30).map(x=>`<div class="row"><div class="grow"><div class="name">${String(x.text||'Изменение рейтинга')}</div><div class="meta">${x.ts?new Date(x.ts).toLocaleString('ru-RU'):''}</div></div></div>`).join('')}</div>`};
const stableHome=m=>{m.innerHTML=news()};
const stableP4P=m=>{ensureP4PPositions();const a=getP4P(),edit=window.__stableP4PEdit===true;m.innerHTML=`<div class="card"><div class="muted">P4P</div><div class="hero" style="font-size:25px">Рейтинг P4P</div><div class="muted">Один боец объединяет все весовые. Позиция сохраняется отдельно.</div><button class="primary" style="margin-top:10px" onclick="window.__stableP4PEdit=!window.__stableP4PEdit;window.render()">${edit?'ОТМЕНИТЬ':'✎ РЕДАКТИРОВАТЬ P4P'}</button>${edit?'<button class="primary stable-save" onclick="window.stableSaveP4P()">СОХРАНИТЬ P4P</button>':''}</div><div class="list stable-p4p-list">${a.slice(0,15).map((x,i)=>`<div class="row stable-p4p-row" data-name="${String(x.name).replace(/"/g,'&quot;')}"><div class="rank">${i+1}</div><div class="flag">${FLAGS[x.country]||'🏳️'}</div><div class="grow" onclick="masterOpenByName('${String(x.name).replace(/'/g,"\\'")}')"><div class="name">${x.name} ${x.titles?('🏆'.repeat(Math.min(2,x.titles))):''}</div><div class="meta">ОБЩИЙ РЕКОРД · ${x.wins}-${x.losses}-${x.draws} · ${x.streak>0?'+'+x.streak+' W':x.streak<0?'-'+Math.abs(x.streak)+' L':'0'} · ${x.activeDefenses} активных защит</div></div>${edit?'<div class="stable-handle" draggable="true">☰</div>':''}<button class="edit" onclick="event.stopPropagation();masterOpenByName('${String(x.name).replace(/'/g,"\\'")}')">✎</button></div>`).join('')}</div><div class="outside"><div class="outsideTitle">За пределами TOP-15</div><div class="list">${a.slice(15).map((x,i)=>`<div class="row"><div class="rank">${i+16}</div><div class="flag">${FLAGS[x.country]||'🏳️'}</div><div class="grow"><div class="name">${x.name}</div><div class="meta">${x.wins}-${x.losses}-${x.draws}</div></div></div>`).join('')}</div></div>`;if(edit)bindStableDrag()};
function bindStableDrag(){document.querySelectorAll('.stable-handle').forEach(h=>h.addEventListener('dragstart',e=>{const r=h.closest('.stable-p4p-row');e.dataTransfer.setData('text/plain',r.dataset.name)}));document.querySelectorAll('.stable-p4p-row').forEach(r=>{r.addEventListener('dragover',e=>e.preventDefault());r.addEventListener('drop',e=>{e.preventDefault();const from=e.dataTransfer.getData('text/plain'),to=r.dataset.name;if(!from||from===to)return;const pos=readJSON(P4P_POS_KEY,{}),ordered=getP4P().slice(0,15).map(x=>x.name),fi=ordered.indexOf(from),ti=ordered.indexOf(to);if(fi<0||ti<0)return;ordered.splice(ti,0,ordered.splice(fi,1)[0]);ordered.forEach((name,i)=>pos[name]=i+1);writeJSON(P4P_POS_KEY,pos);window.render()})})}
window.stableSaveP4P=()=>{backupStable('Перед сохранением P4P v19');const pos=readJSON(P4P_POS_KEY,{});document.querySelectorAll('.stable-p4p-row').forEach((r,i)=>pos[r.dataset.name]=i+1);writeJSON(P4P_POS_KEY,pos);window.__stableP4PEdit=false;window.render()};
const oldRender=window.render;window.render=function(){const m=document.getElementById('main');if(!m)return;if(window.page==='home'){window.weight='P4P';stableHome(m);return}if(window.page==='rank'&&window.weight==='P4P'){stableP4P(m);return}return oldRender.apply(this,arguments)};
const oldAdd=window.addFight;window.addFight=function(){backupStable('Перед добавлением боя');return oldAdd.apply(this,arguments)};
const oldSaveEdit=window.saveEdit;window.saveEdit=function(id){backupStable('Перед редактированием бойца');return oldSaveEdit.apply(this,arguments)};
const style=document.createElement('style');style.textContent='.stable-save{position:fixed;left:12px;right:12px;bottom:78px;z-index:20;box-shadow:0 4px 18px #000}.stable-handle{flex:0 0 34px;width:34px;text-align:center;font-size:22px;color:#aaa;cursor:grab;touch-action:none}.stable-handle:active{cursor:grabbing}.stable-p4p-row .edit{flex:0 0 auto}.stable-p4p-row{min-width:0}.stable-p4p-row .grow{min-width:0}.stable-p4p-row .name,.stable-p4p-row .meta{overflow:hidden;text-overflow:ellipsis}';document.head.appendChild(style);
ensureP4PPositions();
window.__stableP4PVersion=19;
})();
