(()=>{'use strict';
/* FIGHTER RATINGS v22 — persistence + correct streak/defense display. NEVER rewrites records. */
const KEY='ratingDB',P4PKEY='manualP4PPositions_v3',NEWS='rankingNews_v3',BACK='ratingBackups_v3';
const read=(k,d)=>{try{const v=localStorage.getItem(k);return v===null?d:JSON.parse(v)}catch(e){return d}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const backup=(label)=>{const a=read(BACK,[]);a.unshift({label,at:new Date().toISOString(),ratingDB:localStorage.getItem(KEY),p4p:localStorage.getItem(P4PKEY),news:localStorage.getItem(NEWS)});write(BACK,a.slice(0,50));};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const names=window.names||{Heavyweight:'Тяжёлый','Light Heavyweight':'Полутяжёлый',Middleweight:'Средний',Welterweight:'Полусредний',Lightweight:'Лёгкий',Featherweight:'Полулёгкий',Bantamweight:'Легчайший',Flyweight:'Наилегчайший'};
const flags=window.FLAGS||{};
function data(){return Array.isArray(window.F)?window.F:read(KEY,[])}
function backupOnly(label){backup(label)}
function addNews(text){const a=read(NEWS,[]);a.unshift(new Date().toLocaleDateString('ru-RU')+' — '+text);write(NEWS,a.slice(0,80));}
function historyStreak(f){let h=Array.isArray(f.history)?f.history:[];if(!h.length)return 0;let s=0;for(const x of h){if(x.result==='W'||x.result==='WIN')s=s>=0?s+1:1;else if(x.result==='L'||x.result==='LOSS')s=s<=0?s-1:-1;else s=0;}return s}
function streakOf(f){const n=Number(f.streak);return n!==0?n:historyStreak(f)}
function streakText(n){n=Number(n)||0;return n>0?'+'+n+' побед':n<0?n+' поражений':'0'}
function groups(){const m=new Map();for(const f of data()){const k=String(f.name||'').trim().toLocaleLowerCase('ru');if(!m.has(k))m.set(k,{key:k,name:f.name,country:f.country,records:[]});m.get(k).records.push(f)}return [...m.values()]}
function agg(g){let a={wins:0,losses:0,draws:0,activeDefenses:0,titleDefenses:0,titles:0,streak:0};for(const f of g.records){a.wins+=+f.wins||0;a.losses+=+f.losses||0;a.draws+=+f.draws||0;a.activeDefenses+=+f.activeDefenses||0;a.titleDefenses+=+f.titleDefenses||0;a.titles+=f.champion?1:0;const s=streakOf(f);if(s>0&&s>a.streak)a.streak=s;else if(a.streak===0&&s<0)a.streak=s}return a}
function p4p(){const gs=groups(),pos=read(P4PKEY,{}),map=new Map(gs.map(g=>[g.key,g])),out=[];Object.keys(pos).sort((a,b)=>pos[a]-pos[b]).forEach(k=>{const g=map.get(k);if(g){out.push(g);map.delete(k)}});[...map.values()].sort((a,b)=>{const pa=Math.min(...a.records.map(f=>+f.p4pRank||999)),pb=Math.min(...b.records.map(f=>+f.p4pRank||999));return pa-pb||((agg(b).wins-agg(b).losses)-(agg(a).wins-agg(a).losses))||a.name.localeCompare(b.name,'ru')}).forEach(g=>out.push(g));return out}
function ensureOrder(){const pos=read(P4PKEY,null);if(!pos||typeof pos!=='object'||Array.isArray(pos)){const o={};p4p().forEach((g,i)=>o[g.key]=i+1);write(P4PKEY,o)}}ensureOrder();
function p4pRow(g,i,edit){const a=agg(g);return `<div class="row v21-p4p" data-key="${esc(g.key)}"><div class="rank">${i}</div><div class="flag">${flags[g.country]||'🏳️'}</div><div class="grow"><div class="name">${esc(g.name)} ${'🏆'.repeat(Math.min(2,a.titles))}</div><div class="meta">ОБЩИЙ РЕКОРД · ${a.wins}-${a.losses}-${a.draws} · СЕРИЯ ${streakText(a.streak)}${a.activeDefenses?' · '+a.activeDefenses+' акт. защит':''}${a.titleDefenses?' · '+a.titleDefenses+' защит':''} · ${g.records.map(f=>names[f.weight]||f.weight).join(' / ')}</div></div>${edit?'<div class="v21-handle" data-key="'+esc(g.key)+'">☰</div>':''}<button class="edit" onclick="event.stopPropagation();v21Profile(\''+esc(g.records[0].id)+'\')">✎</button></div>`}
function weightRow(f,i,edit){const s=streakOf(f);return `<div class="row v21-weight" data-id="${esc(f.id)}"><div class="rank">${i}</div><div class="flag">${flags[f.country]||'🏳️'}</div><div class="grow" onclick="v21Profile('${esc(f.id)}')"><div class="name">${esc(f.name)} ${f.champion?'🏆':''}</div><div class="meta">${f.wins}-${f.losses}-${f.draws} · СЕРИЯ ${streakText(s)} · ${f.activeDefenses||0} акт. защит · ${f.titleDefenses||0} защит</div></div>${edit?'<div class="v21-handle" data-id="'+esc(f.id)+'">☰</div>':''}<button class="edit" onclick="event.stopPropagation();v21Edit(\''+esc(f.id)+'\')">✎</button></div>`}
let editing=null;
function install(){const old=window.render;if(typeof old!=='function')return;window.render=function(){try{const m=document.getElementById('main');if(window.page==='rank'){const nav=document.getElementById('weights');if(nav&&Array.isArray(window.W))nav.innerHTML=window.W.map(x=>`<button class="${window.weight===x?'on':''}" onclick="weight='${x}';page='rank';render()">${x==='P4P'?'P4P':(names[x]||x)}</button>`).join('');if(window.weight==='P4P')return renderP4P(m);return renderWeight(m)}return old.apply(this,arguments)}catch(e){console.error('v22 render',e);return old.apply(this,arguments)}}}
function renderP4P(m){const a=p4p();m.innerHTML=`<div class="card"><div class="muted">P4P</div><div class="hero" style="font-size:25px">Рейтинг P4P</div><div class="muted">Один боец — одна строка. Рекорд объединяется из всех весов и позиция сохраняется отдельно.</div><button class="primary" style="margin-top:10px" onclick="v21EditP4P()">✎ РЕДАКТИРОВАТЬ P4P</button></div><div class="section">P4P TOP 15</div><div class="list">${a.slice(0,15).map((g,i)=>p4pRow(g,i+1,false)).join('')||'<div class="empty">P4P пуст.</div>'}</div>${a.length>15?'<div class="outside"><div class="outsideTitle">За пределами TOP-15</div><div class="list">'+a.slice(15).map((g,i)=>p4pRow(g,i+16,false)).join('')+'</div></div>':''}`}
function renderWeight(m){const a=data().filter(f=>f.weight===window.weight).sort((x,y)=>(+x.rank||99)-(+y.rank||99)||(+y.wins||0)-(+x.wins||0));const ch=a.filter(f=>f.champion),r=a.filter(f=>!f.champion);m.innerHTML=`<div class="card"><div class="muted">${names[window.weight]||window.weight}</div><div class="hero" style="font-size:25px">Рейтинг</div><div class="muted">Чемпион отдельно · №1 — первый претендент</div><button class="primary" style="margin-top:10px" onclick="v21EditWeight()">✎ РЕДАКТИРОВАТЬ РЕЙТИНГ</button></div><div class="section">🏆 ЧЕМПИОН</div><div class="list">${ch.map(f=>weightRow(f,'🏆',false)).join('')||'<div class="empty">Пояс вакантен</div>'}</div><div class="section">№1–15 ПРЕТЕНДЕНТЫ</div><div class="list">${r.slice(0,15).map((f,i)=>weightRow(f,i+1,false)).join('')}</div>${r.length>15?'<div class="outside"><div class="outsideTitle">За пределами TOP-15</div><div class="list">'+r.slice(15).map((f,i)=>weightRow(f,i+16)).join('')+'</div></div>':''}`}
function addFixedSave(){let s=document.getElementById('v21save');if(!s){s=document.createElement('div');s.id='v21save';s.style='position:fixed;left:0;right:0;bottom:70px;z-index:9999;padding:8px 12px;background:linear-gradient(#08090a00,#08090af5)';document.body.appendChild(s)}s.innerHTML='<button style="width:100%;background:#eee;color:#08090a;font-weight:900;padding:13px;border:0;border-radius:10px" onclick="v21SaveEditor()">СОХРАНИТЬ ИЗМЕНЕНИЯ</button>';s.style.display='block'}
function removeFixedSave(){const s=document.getElementById('v21save');if(s)s.style.display='none'}
function v21EditP4P(){editing={type:'p4p',list:p4p().map(g=>g.key),before:p4p().map(g=>g.key)};addFixedSave();const gs=new Map(groups().map(g=>[g.key,g]));document.getElementById('main').innerHTML='<div class="card"><div class="hero" style="font-size:24px">Редактор P4P</div><div class="muted">Тяни ☰ справа. Ничего не пересчитывается автоматически.</div><button onclick="v21Cancel()">Отмена</button></div><div id="v21list" class="list">'+editing.list.map((k,i)=>p4pRow(gs.get(k),i+1,true)).join('')+'</div>';bindTouch('p4p')}
function v21EditWeight(){const a=data().filter(f=>f.weight===window.weight).sort((x,y)=>(+x.rank||99)-(+y.rank||99));editing={type:'weight',list:a.map(f=>f.id),before:a.map(f=>f.id)};addFixedSave();document.getElementById('main').innerHTML='<div class="card"><div class="hero" style="font-size:24px">Редактор '+(names[window.weight]||window.weight)+'</div><div class="muted">Тяни ☰ справа. Чемпионство меняй в профиле.</div><button onclick="v21Cancel()">Отмена</button></div><div id="v21list" class="list">'+a.map((f,i)=>weightRow(f,i+1,true)).join('')+'</div>';bindTouch('weight')}
function bindTouch(type){document.querySelectorAll('.v21-handle').forEach(h=>h.addEventListener('pointerdown',e=>{e.preventDefault();h.setPointerCapture?.(e.pointerId);window.__v21drag={row:h.closest('.row'),type};window.__v21drag.row.classList.add('dragging');document.addEventListener('pointermove',move);document.addEventListener('pointerup',end,{once:true})}));function move(e){const d=window.__v21drag;if(!d)return;const rows=[...document.querySelectorAll('#v21list .row:not(.dragging)')];const target=rows.find(r=>{const b=r.getBoundingClientRect();return e.clientY<b.top+b.height/2});if(target)target.before(d.row);else document.getElementById('v21list').appendChild(d.row)}function end(){const d=window.__v21drag;if(!d)return;d.row.classList.remove('dragging');const rows=[...document.querySelectorAll('#v21list .row')];editing.list=rows.map(r=>d.type==='p4p'?r.dataset.key:r.dataset.id);window.__v21drag=null;document.removeEventListener('pointermove',move)}}
window.v21SaveEditor=()=>{if(!editing)return;backupOnly('Перед сохранением редактора');const rows=[...document.querySelectorAll('#v21list .row')];if(editing.type==='p4p'){const pos={};rows.forEach((r,i)=>pos[r.dataset.key]=i+1);write(P4PKEY,pos);editing.before.forEach(k=>{const old=editing.before.indexOf(k),nu=editing.list.indexOf(k);if(old!==nu){const g=groups().find(x=>x.key===k);if(g)addNews(`${g.name} ${nu<old?'поднялся':'опустился'} на P4P #${nu+1}`)}})}else{rows.forEach((r,i)=>{const f=data().find(x=>String(x.id)===String(r.dataset.id));if(f)f.rank=i+1});editing.before.forEach(id=>{const old=editing.before.indexOf(id),nu=editing.list.indexOf(id);if(old!==nu){const f=data().find(x=>String(x.id)===String(id));if(f)addNews(`${f.name} ${nu<old?'поднялся':'опустился'} с #${old+1} на #${nu+1} в ${names[window.weight]||window.weight}`)}})}localStorage.setItem(KEY,JSON.stringify(data()));editing=null;removeFixedSave();window.page='rank';window.render();};
window.v21Cancel=()=>{editing=null;removeFixedSave();window.render()};
function v21Edit(id){if(typeof window.editFighter==='function')return window.editFighter(id)}function v21Profile(id){if(typeof window.openProfile==='function')return window.openProfile(id)}
window.v21Edit=v21Edit;window.v21Profile=v21Profile;window.v21EditP4P=v21EditP4P;window.v21EditWeight=v21EditWeight;install();
})();
