(()=>{
const style=document.createElement('style');style.textContent=`#pageHome .rankings,#home .rankings,.home-rankings{display:none!important}.rank-edit-bar{position:fixed;left:12px;right:12px;bottom:76px;z-index:9999;display:flex;gap:8px;justify-content:center;background:rgba(10,14,20,.98);padding:10px;border:1px solid #292c30;border-radius:14px;box-shadow:0 6px 25px #0008}.rank-edit-bar button{flex:1;max-width:240px}.drag-handle{width:38px!important;min-width:38px;height:38px;padding:0!important;display:inline-flex!important;align-items:center;justify-content:center;font-size:20px;touch-action:none;cursor:grab}.ranking-row{position:relative}.ranking-row.dragging{opacity:.45}.ranking-row.drag-over{outline:2px solid #fff6}`;document.head.appendChild(style);
function persist(){try{localStorage.setItem('ratingDB',JSON.stringify(F));if(typeof save==='function')save()}catch(e){}}
function news(type,name,from,to,division){let n=JSON.parse(localStorage.getItem('ratingNews')||'[]');let text=type==='champ'?`🏆 ${name} возглавил рейтинг${division?' — '+division:''}`:`${to<from?'⬆️':'⬇️'} ${name} ${to<from?'поднялся':'опустился'} с №${from} на №${to}`;n.unshift({text,date:new Date().toLocaleDateString('ru-RU')});localStorage.setItem('ratingNews',JSON.stringify(n.slice(0,50)))}
function addFixedSave(kind,saveFn){document.querySelector('.rank-edit-bar')?.remove();let b=document.createElement('div');b.className='rank-edit-bar';let x=document.createElement('button');x.className='primary';x.textContent=kind==='p4p'?'СОХРАНИТЬ P4P':'СОХРАНИТЬ РЕЙТИНГ';x.onclick=()=>{saveFn();persist();b.remove();if(typeof render==='function')render()};let c=document.createElement('button');c.textContent='ГОТОВО';c.onclick=()=>b.remove();b.append(x,c);document.body.appendChild(b)}
window.startInlineRankEdit=function(weight){let rows=[...document.querySelectorAll('.ranking-row,[data-fighter-id]')].filter(x=>x.dataset.fighterId);if(!rows.length)return;rows.forEach((r,i)=>{r.draggable=true;r.classList.add('ranking-row');let h=r.querySelector('.drag-handle');if(!h){h=document.createElement('button');h.className='drag-handle';h.textContent='☰';h.title='Перетащить';r.appendChild(h)}r.ondragstart=()=>{r.classList.add('dragging');r.dataset.oldRank=i+1};r.ondragend=()=>{r.classList.remove('dragging');r.classList.remove('drag-over')};r.ondragover=e=>{e.preventDefault();r.classList.add('drag-over')};r.ondragleave=()=>r.classList.remove('drag-over');r.ondrop=e=>{e.preventDefault();let d=document.querySelector('.dragging');if(!d||d===r)return;r.parentNode.insertBefore(d,r);r.classList.remove('drag-over');let all=[...r.parentNode.querySelectorAll('.ranking-row')];all.forEach((el,j)=>{let id=+el.dataset.fighterId,f=F.find(z=>z.id===id);if(f){let old=f.rank;f.rank=j+1;if(old!==j+1)news('move',f.name,old,j+1,weight)}})};});addFixedSave(weight==='P4P'?'p4p':'weight',()=>{let parents=[...document.querySelectorAll('.ranking-row')];parents.forEach((el,j)=>{let f=F.find(z=>z.id===+el.dataset.fighterId);if(f)f.rank=j+1});persist()})}
window.startP4PEdit=function(){startInlineRankEdit('P4P');let b=document.querySelector('.rank-edit-bar');if(b)b.querySelector('button').textContent='СОХРАНИТЬ P4P'};
window.renderNews=function(){let n=JSON.parse(localStorage.getItem('ratingNews')||'[]');return n.map(x=>`<div class="card"><b>📰 Новости рейтингов</b><div>${x.text}</div><small class="muted">${x.date}</small></div>`).join('')||'<div class="muted">Пока нет изменений рейтингов</div>'};
window.persistStats=(id,vals)=>{let f=F.find(x=>x.id==id);if(!f)return;Object.assign(f,vals);persist()};
})();
