(function(){
  function num(v,d=0){const n=Number(v);return Number.isFinite(n)?n:d}
  function saveDB(){if(typeof save==='function')save();else localStorage.setItem('ratingDB',JSON.stringify(F));}
  function close(){if(typeof closeModal==='function')closeModal();else document.getElementById('modal')?.classList.remove('show')}
  window.openRankingEditor=function(){
    const modal=document.getElementById('modal'), box=document.getElementById('modalContent'); if(!modal||!box)return;
    if(weight==='P4P')return window.openP4PEditor();
    const a=F.filter(f=>f.weight===weight).slice().sort((x,y)=>(num(x.rank,999)-num(y.rank,999))||x.name.localeCompare(y.name,'ru'));
    box.innerHTML='<h2>✎ Редактор '+(names[weight]||weight)+'</h2><div class="muted">Меняй позиции и чемпионство.</div>'+a.map(f=>`<div class="card"><b>${flag(f)} ${f.name}</b><div class="muted">${num(f.wins)}-${num(f.losses)}-${num(f.draws)}</div><label>Позиция</label><input class="hot-rank" data-id="${f.id}" type="number" min="1" value="${num(f.rank,999)}"><label><input class="hot-champ" data-id="${f.id}" type="checkbox" ${f.champion?'checked':''}> Чемпион</label></div>`).join('')+'<div style="position:sticky;bottom:0;background:#111315;padding:10px 0"><button class="primary" id="hot-save-rank">СОХРАНИТЬ РЕЙТИНГ</button></div>';
    document.getElementById('hot-save-rank').onclick=function(){let champ=null;document.querySelectorAll('.hot-rank').forEach(e=>{const f=F.find(x=>String(x.id)===e.dataset.id);if(f)f.rank=Math.max(1,num(e.value,999))});document.querySelectorAll('.hot-champ').forEach(e=>{if(e.checked)champ=F.find(x=>String(x.id)===e.dataset.id)});F.filter(f=>f.weight===weight).forEach(f=>f.champion=!!champ&&f.id===champ.id);saveDB();close();render()};
    modal.classList.add('show');
  };
  window.openP4PEditor=function(){
    const modal=document.getElementById('modal'),box=document.getElementById('modalContent');if(!modal||!box)return;
    const a=window.p4p();
    box.innerHTML='<h2>✎ Редактор P4P</h2><div class="muted">Позиция P4P сохраняется отдельно.</div>'+a.map((f,i)=>`<div class="card"><b>${flag({country:f.country})} ${f.name}</b><div class="muted">${num(f.wins)}-${num(f.losses)}-${num(f.draws)} · ${f.championCount?'🏆'.repeat(Math.min(3,f.championCount)):''}</div><label>P4P позиция</label><input class="hot-p4p" data-name="${encodeURIComponent(f.name)}" type="number" min="1" value="${num(f.p4pRank,i+1)}"></div>`).join('')+'<div style="position:sticky;bottom:0;background:#111315;padding:10px 0"><button class="primary" id="hot-save-p4p">СОХРАНИТЬ P4P</button></div>';
    document.getElementById('hot-save-p4p').onclick=function(){document.querySelectorAll('.hot-p4p').forEach(e=>{const k=decodeURIComponent(e.dataset.name).trim().toLowerCase(),r=Math.max(1,num(e.value,999));F.filter(f=>f.name.trim().toLowerCase()===k).forEach(f=>f.p4pRank=r)});saveDB();close();render()};
    modal.classList.add('show');
  };
  window.editFighter=function(id){
    const f=F.find(x=>String(x.id)===String(id));const box=document.getElementById('modalContent'),modal=document.getElementById('modal');if(!f||!box||!modal)return;
    box.innerHTML=`<h2>✎ ${flag(f)} ${f.name}</h2><label>Вес</label><select id="hf-w">${W.filter(x=>x!=='P4P').map(w=>`<option value="${w}" ${f.weight===w?'selected':''}>${names[w]}</option>`).join('')}</select><label>Победы</label><input id="hf-win" type="number" min="0" value="${num(f.wins)}"><label>Поражения</label><input id="hf-loss" type="number" min="0" value="${num(f.losses)}"><label>Ничьи</label><input id="hf-draw" type="number" min="0" value="${num(f.draws)}"><label>Серия (+/-)</label><input id="hf-streak" type="number" value="${num(f.streak)}"><label>Общие защиты</label><input id="hf-def" type="number" min="0" value="${num(f.titleDefenses)}"><label>Активные защиты</label><input id="hf-adef" type="number" min="0" value="${num(f.activeDefenses)}"><label>Завоеваний пояса</label><input id="hf-tw" type="number" min="0" value="${num(f.titleWins)}"><label>Позиция</label><input id="hf-rank" type="number" min="1" value="${num(f.rank,999)}"><label>P4P</label><input id="hf-p4p" type="number" min="1" value="${f.p4pRank||''}"><label><input id="hf-champ" type="checkbox" ${f.champion?'checked':''}> Чемпион</label><div style="position:sticky;bottom:0;background:#111315;padding:10px 0"><button class="primary" id="hf-save">СОХРАНИТЬ БОЙЦА</button></div>`;
    document.getElementById('hf-save').onclick=function(){f.weight=document.getElementById('hf-w').value;f.wins=num(document.getElementById('hf-win').value);f.losses=num(document.getElementById('hf-loss').value);f.draws=num(document.getElementById('hf-draw').value);f.streak=num(document.getElementById('hf-streak').value);f.titleDefenses=num(document.getElementById('hf-def').value);f.activeDefenses=num(document.getElementById('hf-adef').value);f.titleWins=num(document.getElementById('hf-tw').value);f.rank=Math.max(1,num(document.getElementById('hf-rank').value,999));const p=num(document.getElementById('hf-p4p').value);f.p4pRank=p>0?p:null;f.champion=document.getElementById('hf-champ').checked;saveDB();close();render()};
    modal.classList.add('show');
  };
  window.addFight=function(){
    const s=document.getElementById('bf')||document.getElementById('f'),r=document.getElementById('br')||document.getElementById('r');if(!s||!r)return alert('Выбери бойца и результат');const f=F.find(x=>String(x.id)===String(s.value));if(!f)return alert('Боец не найден');const res=r.value==='W'||r.value==='1'||r.value==='WIN'?'W':r.value==='L'||r.value==='0'||r.value==='LOSS'?'L':'D';const was=f.champion;f.history=f.history||[];const method=document.getElementById('bm')?.value||'',round=document.getElementById('bround')?.value||'';if(res==='W'){f.wins=num(f.wins)+1;f.streak=f.streak>0?f.streak+1:1;if(was){f.titleDefenses=num(f.titleDefenses)+1;f.activeDefenses=num(f.activeDefenses)+1}f.history.unshift({result:'W',method,round,date:new Date().toLocaleDateString('ru-RU')})}else if(res==='L'){f.losses=num(f.losses)+1;f.streak=f.streak<0?f.streak-1:-1;if(was){f.champion=false;f.activeDefenses=0;const c=F.filter(x=>x.weight===f.weight&&!x.champion&&num(x.streak)>=2).sort((a,b)=>(num(a.rank,999)-num(b.rank,999))||num(b.streak)-num(a.streak))[0];if(c)c.champion=true}f.history.unshift({result:'L',method,round,date:new Date().toLocaleDateString('ru-RU')})}else{f.draws=num(f.draws)+1;f.streak=0;f.history.unshift({result:'D',method,round,date:new Date().toLocaleDateString('ru-RU')})}saveDB();weight=f.weight;page='rank';render();
  };
  const oldRank=window.rank; if(oldRank){window.rank=function(m){oldRank(m);const c=m.querySelector('.card');if(c&&!c.querySelector('.hot-rank-btn')){const b=document.createElement('button');b.className='primary hot-rank-btn';b.style.marginTop='10px';b.textContent='✎ РЕДАКТИРОВАТЬ РЕЙТИНГ';b.onclick=function(){weight==='P4P'?openP4PEditor():openRankingEditor()};c.appendChild(b)}}}
})();